version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=desafio-trasus-arg;User Id=postgres;Password=gustavo10"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio-trasus-arg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gustavo10
